---
# tasks file for role-tasktempalte-config
# Task Section
- name: "Install httpd on {{ host_name }}"
  yum:
    name: httpd
    state: installed
  become: yes
  notify: Restart HTTPD

# Handlers section
handlers:
- name: Restart HTTPD
  service:
    name: httpd
    state: restarted

  
