---
# tasks file for role-tasktempalte-config
# Task Section

- name: Date/Time stamp when playbook started
  raw: /usr/bin/date
  register: date
- debug: 
    msg: "{{ date.stdout_lines }}"

- name: Async polling the task - test
  command: /bin/sleep 25
  async: 45
  poll: 5
  register: sleep_result

- name: "Install httpd on {{ host_name }}"
  yum:
    name: httpd
    state: installed
  become: yes
  notify: 
  - Restart HTTPD

- name: STATUS - Async polling the task - test
  async_status:
    jid: "{{ sleep_result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 10
  delay: 10
- debug:
    msg: "{{ lookup('env', 'PATH') }}"
  when: ansible_os_family == "RedHat"

- name: Install Apache
  yum:
    name: httpd
    state: latest

- name: Start and enable Apache service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Create index.html file
  file:
    path: /var/www/html/index.html
    state: touch

# This module is used to insert lines to the files in the target hosts
- name: Add line to index.html
  lineinfile:
    path: /var/www/html/index.html
    line: "Hello World"